import { CustomLocationSet } from '../types';

export const AGENTEN_LOCATION_SETS: CustomLocationSet[] = [
    {
        name: 'Geheimdienste',
        locations: [
            "Eine Militärbasis",
            "Ein geheimes Untergrund-Turnier",
            "Das Weiße Haus",
            "Eine antarktische Forschungsstation",
            "Ein Tiefseelabor",
            "Ein Hochsicherheitsgefängnis",
            "Ein Atombunker",
            "Ein Spionage-Hauptquartier",
            "Ein verlassenes Forschungslabor",
            "Eine geheime Waffenfabrik",
            "Ein Überwachungszentrum",
            "Ein Tresorraum",
            "Ein Regierungsarchiv",
            "Eine geheime Inselbasis",
            "Ein Blacksite-Gefängnis",
            "Ein Cyber-Kommandozentrum",
            "Ein Trainingslager für Spezialagenten",
            "Ein unterirdischer Serverpark",
            "Eine verdeckte Operationseinheit",
            "Ein Satellitenkontrollzentrum"
        ]
    },
    {
        name: 'Luxusorte',
        locations: [
            "Ein Casino in Las Vegas",
            "Ein Luxushotel",
            "In der Oper",
            "Ein Weingut",
            "Ein Kreuzfahrtschiff",
            "Eine Luxusjacht",
            "Ein Penthouse in New York",
            "Ein exklusiver Privatclub",
            "Eine Kunstauktion",
            "Ein Mode-Laufsteg",
            "Ein Gourmet-Restaurant",
            "Eine Filmpremiere",
            "Ein exklusives Spa",
            "Ein Polo-Club",
            "Ein Juweliergeschäft",
            "Ein Formel-1-Rennen",
            "Ein High-End-Technik-Event",
            "Eine private Kunstgalerie",
            "Ein Luxus-Shoppingcenter",
            "Ein Gala-Dinner"
        ]
    },
    {
        name: 'Natur',
        locations: [
            "Eine Vulkaninsel",
            "Ein Iglu",
            "Eine antarktische Forschungsstation",
            "Ein tropischer Regenwald",
            "Die Sahara-Wüste",
            "Ein Bergpass in den Alpen",
            "Eine Eishöhle",
            "Ein Korallenriff",
            "Ein tiefer Canyon",
            "Eine verlassene Goldmine",
            "Ein aktiver Vulkan",
            "Ein Geysirfeld",
            "Eine einsame Insel",
            "Ein Sumpfgebiet",
            "Eine Tundra-Landschaft",
            "Ein Unterwasser-Vulkankrater",
            "Ein riesiges Höhlensystem",
            "Ein Treibsandfeld",
            "Eine Oase",
            "Ein Fjord"
        ]
    },
    {
        name: 'Öffentlich',
        locations: [
            "Ein Zoo",
            "Eine Bibliothek",
            "Ein Krankenhaus",
            "Eine Bank",
            "Ein Supermarkt",
            "Ein Einkaufszentrum",
            "Ein Bahnhof",
            "Ein Flughafen-Terminal",
            "Ein belebter Stadtplatz",
            "Ein Museum",
            "Ein Park",
            "Ein Sportstadion",
            "Eine Universität",
            "Ein Gerichtssaal",
            "Ein Postamt",
            "Eine Polizeistation",
            "Eine Feuerwache",
            "Ein Busbahnhof",
            "Eine U-Bahn-Station",
            "Ein öffentliches Schwimmbad"
        ]
    },
    {
        name: 'Transport',
        locations: [
            "Auf einem U-Boot",
            "Ein Kreuzfahrtschiff",
            "Ein Polarexpress",
            "Ein Ufo",
            "In einer Zeitmaschine",
            "Ein Frachtschiff",
            "Ein Güterzug",
            "Ein Heißluftballon",
            "Ein Privatjet",
            "Ein Hubschrauber",
            "Eine Fähre",
            "Ein Raumschiff (nicht ISS)",
            "Eine Seilbahn",
            "Ein Unterwasserfahrzeug",
            "Ein Panzer",
            "Ein Amphibienfahrzeug",
            "Ein Luftschiff",
            "Ein Jetpack-Flug",
            "Ein Hochgeschwindigkeitszug",
            "Ein Containerschiff"
        ]
    },
    {
        name: 'Forschung',
        locations: [
            "Eine Raumstation",
            "Die Internationale Raumstation ISS",
            "Ein Tiefseelabor",
            "Auf dem Mars",
            "Ein Künstleratelier",
            "Eine Genforschungseinrichtung",
            "Ein Teilchenbeschleuniger",
            "Ein Robotik-Labor",
            "Eine Wetterforschungsstation",
            "Ein Seismologisches Institut",
            "Ein Astronomisches Observatorium",
            "Ein Virenforschungslabor",
            "Ein Archäologisches Ausgrabungsfeld",
            "Ein Quantenphysik-Labor",
            "Eine KI-Entwicklungsfirma",
            "Ein Botanisches Forschungsgewächshaus",
            "Ein Geologisches Feldcamp",
            "Ein Unterwasser-Forschungslabor",
            "Ein Kryptozoologie-Institut",
            "Eine Plasma-Forschungsanlage"
        ]
    },
    {
        name: 'Kultur',
        locations: [
            "Ein Filmset in Hollywood",
            "Eine Zirkusmanege",
            "Eine Geisterbahn auf dem Jahrmarkt",
            "Backstage bei einem Rockkonzert",
            "Ein Film-Noir-Detektivbüro",
            "Ein Bällebad für Kinder",
            "In der Oper",
            "Ein Theater",
            "Ein Comedy-Club",
            "Ein Musikstudio",
            "Ein Kunstmuseum",
            "Ein Vergnügungspark",
            "Ein Escape Room",
            "Ein Videospiel-Turnier",
            "Eine Comic-Con",
            "Ein Mittelaltermarkt",
            "Ein Straßenfest",
            "Ein Puppentheater",
            "Ein Tanzstudio",
            "Eine Karaoke-Bar"
        ]
    },
    {
        name: 'Historisch & Mystisch',
        locations: [
            "Eine antike Pyramide",
            "Eine Ritterburg",
            "Ein Ufo",
            "In einer Zeitmaschine",
            "Ein verlassenes Kloster",
            "Ein alter Friedhof",
            "Ein verwunschenes Herrenhaus",
            "Ein antiker Tempel",
            "Ein verfallenes Kolosseum",
            "Ein Geisterdorf",
            "Ein Stonehenge-ähnlicher Steinkreis",
            "Eine versunkene Stadt (Atlantis)",
            "Ein Portal zu einer anderen Dimension",
            "Ein Hexenwald",
            "Ein mythischer Berg (Olymp)",
            "Ein verbotener Tempel",
            "Ein Drachenhort",
            "Ein Elfenwald",
            "Ein Ort alter Rituale",
            "Ein Zeitreise-Labor"
        ]
    },
    {
        name: 'Produktion',
        locations: [
            "In einer Schokoladenfabrik",
            "Eine Parfüm-Fabrik",
            "Eine Autofabrik",
            "Eine Brauerei",
            "Eine Druckerei",
            "Eine Spielzeugfabrik",
            "Eine Textilfabrik",
            "Eine Chemiefabrik",
            "Eine Glasbläserei",
            "Eine Bäckerei",
            "Ein Stahlwerk",
            "Ein Sägewerk",
            "Eine Papierfabrik",
            "Eine Chipfabrik",
            "Eine Batteriefabrik",
            "Eine Waffenfabrik",
            "Eine Medikamentenfabrik",
            "Eine Lebensmittelverarbeitungsanlage",
            "Eine Windkraftanlagenproduktion",
            "Ein Rechenzentrum"
        ]
    }
];
