import { CustomTruthOrDareSet } from '../types';

export const TRUTH_OR_DARE_SETS: CustomTruthOrDareSet[] = [
    {
        name: 'Harmlos',
        wahrheit: [
            "Was war der peinlichste Moment in deiner Schulzeit?",
            "Welche Superkraft hättest du am liebsten?",
            "Wenn du ein Tier sein könntest, welches wärst du?",
            "Was ist dein heimliches Vergnügen (Guilty Pleasure)?",
            "Was war das kindischste, was du diese Woche getan hast?",
            "Worüber hast du zuletzt herzhaft gelacht?",
            "Was ist dein seltsamstes Talent?",
            "Was ist die seltsamste Essenskombination, die du magst?",
            "Welchen fiktiven Charakter würdest du heiraten?",
            "Wenn du für einen Tag unsichtbar wärst, was würdest du tun?",
            "Was ist das peinlichste Lied auf deiner Playlist?",
            "Was war das lustigste Missverständnis, das du je hattest?",
            "Wenn du eine Zeitreise machen könntest, wohin würdest du zuerst reisen?",
            "Was ist das Wertvollste, das du besitzt (nicht-monetär)?",
            "Was ist dein Lieblings-Cartoonserie aus der Kindheit?",
            "Wenn du eine Woche lang mit einer Berühmtheit tauschen könntest, wer wäre es?",
            "Was ist das Verrückteste, das du je gegessen hast?",
            "Was ist dein größter Tick oder deine größte Marotte?",
            "Was ist das lustigste Gerücht, das du je über dich gehört hast?",
            "Wenn du ein Instrument lernen müsstest, welches wäre es?"
        ],
        pflicht: [
            "Imitiere dein Lieblingstier so überzeugend wie möglich.",
            "Singe 'Alle meine Entchen' in einer Opernstimme.",
            "Versuche, mit deinen Ellenbogen deinen Namen in die Luft zu schreiben.",
            "Gehe auf allen Vieren zum Kühlschrank und wieder zurück.",
            "Erzähle einen Witz. Wenn niemand lacht, musst du selbst laut loslachen.",
            "Balanciere einen Löffel für eine Minute auf deiner Nase.",
            "Rede für die nächsten 5 Minuten nur in Reimen.",
            "Mache der Person dir gegenüber ein möglichst kreatives Kompliment.",
            "Trage für die nächsten drei Runden deine Socken an den Händen.",
            "Tanze einen improvisierten Tanz für 30 Sekunden.",
            "Mache 10 Liegestütze.",
            "Versuche, deine Zunge an deine Nase zu bekommen.",
            "Erzähle eine Kurzgeschichte mit nur drei Wörtern.",
            "Gib der Person links von dir eine Nackenmassage.",
            "Stelle dich für 10 Sekunden auf ein Bein und singe ein Lied.",
            "Mache ein Selfie mit der lustigsten Grimasse, die du machen kannst.",
            "Laufe einmal um den Raum und tue so, als wärst du ein Roboter.",
            "Versuche, ohne Hände ein Glas Wasser zu trinken.",
            "Erzähle eine Anekdote aus deiner Kindheit, die niemand kennt.",
            "Mache eine Minute lang Geräusche wie ein Huhn."
        ],
    },
    {
        name: 'Party',
        wahrheit: [
            "Was war der verrückteste Ort, an dem du jemals aufgewacht bist?",
            "Erzähle von deinem schlimmsten Kater.",
            "Wer in dieser Runde würde einen Zombie-Apokalypse am ehesten überleben?",
            "Was ist das Peinlichste, das deine Eltern über dich wissen?",
            "Was ist das Verrückteste, das du für Geld tun würdest?",
            "Wann hast du das letzte Mal jemanden angelogen und warum?",
            "Was ist das illegalste, was du je getan hast?",
            "Mit wem in diesem Raum würdest du am liebsten für einen Tag das Leben tauschen?",
            "Was ist das Verrückteste, das du je auf einer Party erlebt hast?",
            "Was ist dein größtes Geheimnis, das niemand in diesem Raum kennt?",
            "Wenn du jemanden aus dieser Runde daten müsstest, wer wäre es und warum?",
            "Was ist das Unangenehmste, das du je tun musstest, um aus einer Situation herauszukommen?",
            "Was ist das Teuerste, das du je verloren oder kaputt gemacht hast?",
            "Was ist die größte Lüge, die du je erzählt hast?",
            "Was ist das Verrückteste, das du je im Rausch getan hast?",
            "Wenn du eine Person aus dieser Runde heiraten müsstest, wen würdest du wählen?",
            "Was ist das Schlimmste, das du je gegessen hast, um jemanden zu beeindrucken?",
            "Was ist das Ungewöhnlichste, das du in deinem Kühlschrank hast?",
            "Was ist das Peinlichste, das du je in der Öffentlichkeit getan hast?",
            "Wenn du ein Prominenter wärst, wer wäre es und warum?"
        ],
        pflicht: [
            "Poste ein peinliches altes Foto von dir auf Social Media.",
            "Lass die Person links von dir eine peinliche Nachricht an einen deiner Kontakte schicken.",
            "Trinke einen Shot aus einer ungewöhnlichen Flüssigkeitsmischung (nicht-alkoholisch), die die Gruppe zusammenstellt.",
            "Tanze für eine Minute ohne Musik.",
            "Rufe deine Eltern an und sage ihnen, wie sehr du sie liebst, ohne weiteren Kontext.",
            "Gib jemandem in der Runde eine 2-minütige Kopfmassage.",
            "Wähle eine Person. Ihr müsst euch für 30 Sekunden tief in die Augen schauen, ohne zu lachen.",
            "Mache einen improvisierten Rap über die Person links von dir.",
            "Tausche ein Kleidungsstück mit der Person rechts von dir.",
            "Laufe eine Runde um den Raum und grüße jeden mit einem High Five.",
            "Spiele 'Luftgitarre' zu deinem Lieblingssong.",
            "Mache ein Foto von dir, wie du eine Banane als Telefon benutzt.",
            "Erzähle der Gruppe eine peinliche Geschichte aus deiner Kindheit.",
            "Versuche, ein Glas Wasser auf deinem Kopf zu balancieren und einmal zu gehen.",
            "Mache einen Handstand oder einen Versuch davon.",
            "Gib der Person gegenüber ein Kompliment, das sie zum Erröten bringt.",
            "Singe den Refrain deines Lieblingsliedes lautstark.",
            "Laufe rückwärts durch den Raum.",
            "Iss einen Löffel Senf.",
            "Mache der Person rechts von dir eine Frisur."
        ],
    },
    {
        name: 'Hot & Spicy',
        isAdult: true,
        wahrheit: [
            "Was ist deine wildeste Fantasie?",
            "An welchem öffentlichen Ort hattest du schon mal Sex?",
            "Wer in dieser Runde ist am ehesten dein Typ?",
            "Was ist das Kinkigste, das du je ausprobiert hast?",
            "Beschreibe deinen letzten Orgasmus mit einem Filmtitel.",
            "Wie viele Sexpartner hattest du schon?",
            "Was ist dein größter sexueller Turn-On?",
            "Und was ist dein größter sexueller Abturner?",
            "Was ist die peinlichste Sache, die dir jemals während des Sex passiert ist?",
            "Welches Körperteil findest du an anderen am attraktivsten?",
            "Was ist das Ungezogenste, das du je getan hast, ohne erwischt zu werden?",
            "Wenn du mit einer Person in diesem Raum schlafen müsstest, wer wäre es?",
            "Was ist dein Geheimnis, das deine Freunde nicht wissen?",
            "Was ist das Verrückteste, das du je für Sex getan hast?",
            "Was ist das Schlimmste, das dir je in einer Beziehung passiert ist?",
            "Was ist deine größte sexuelle Angst?",
            "Wenn du eine Nacht mit einer Berühmtheit verbringen könntest, wer wäre es?",
            "Was ist das Anzüglichste, das du je geträumt hast?",
            "Was ist das Verrückteste, das du je in einem Bett getan hast?",
            "Was ist deine Lieblings-Sexstellung?"
        ],
        pflicht: [
            "Gib der Person gegenüber einen sinnlichen Kuss auf den Hals.",
            "Entferne ein Kleidungsstück deiner Wahl.",
            "Zeige der Gruppe die letzte anzügliche Nachricht auf deinem Handy.",
            "Massiere die Füße der Person rechts von dir für eine Minute.",
            "Flüstere einer Person deiner Wahl etwas Anzügliches ins Ohr.",
            "Lecke einer Person deiner Wahl genüsslich Schlagsahne vom Finger.",
            "Gib jemandem deiner Wahl einen Lapdance für 30 Sekunden zu einem imaginären Song.",
            "Wähle eine Person und küsse sie an einer Stelle ihrer Wahl (außer Mund und Genitalbereich).",
            "Mache 10 Sekunden lang Augenkontakt mit der Person gegenüber, ohne zu blinzeln.",
            "Tausche für den Rest der Runde deine Hose mit der Person links von dir.",
            "Erzähle eine sehr kurze, aber anzügliche Geschichte.",
            "Lasse die Person rechts von dir dein Handy entsperren und die letzte App öffnen.",
            "Mache einen 'Catwalk' durch den Raum.",
            "Lasse die Person gegenüber dein Make-up auftragen (oder dir ein 'Gesicht' malen).",
            "Mache 20 Kniebeugen.",
            "Imitiere eine berühmte Person, die ein erotisches Geräusch macht.",
            "Lege dich auf den Boden und tue so, als wärst du ein brutzelndes Stück Speck.",
            "Gib der Person links von dir einen 'sexy' Blick für 10 Sekunden.",
            "Erzähle der Gruppe, was du als Erstes tun würdest, wenn du nackt auf einer belebten Straße aufwachst.",
            "Mache der Person gegenüber ein Kompliment über etwas, das du an ihr attraktiv findest."
        ]
    },
    {
        name: 'Reise & Abenteuer',
        wahrheit: [
            "Was ist das verrückteste, das du je auf einer Reise gegessen hast?",
            "Welches Land möchtest du unbedingt noch bereisen und warum?",
            "Erzähle von einer peinlichen Situation, die du wegen einer Sprachbarriere hattest.",
            "Hast du jemals etwas aus einem Hotelzimmer mitgenommen?",
            "Was war das abenteuerlichste, das du je im Urlaub gemacht hast?",
            "An welchem Ort hast du dich am meisten verloren gefühlt?",
            "Welcher Urlaub war ein totaler Reinfall?",
            "Hast du schon mal einen Flug oder Zug verpasst?",
            "Was ist das Seltsamste, das du als Souvenir gekauft hast?",
            "Würdest du lieber einen Strandurlaub oder einen Städtetrip machen?"
        ],
        pflicht: [
            "Tue so, als wärst du ein Flugbegleiter und mache eine Sicherheitsansage.",
            "Versuche, der Gruppe mit Händen und Füßen dein Traumreiseziel zu erklären.",
            "Packe einen imaginären Koffer für eine Reise in die Antarktis.",
            "Bestelle in einer Fantasiesprache ein Getränk.",
            "Gehe wie ein Tourist, der zum ersten Mal eine riesige Sehenswürdigkeit sieht.",
            "Mache ein Foto von dir, wie du auf einem imaginären Surfbrett reitest.",
            "Frage die Person rechts von dir nach dem Weg zum nächsten Bahnhof - aber nur mit Körpersprache.",
            "Baue aus Gegenständen im Raum den Eiffelturm nach.",
            "Singe eine Strophe eines bekannten Liedes mit einem ausländischen Akzent deiner Wahl.",
            "Tue so, als würdest du durch eine Sicherheitskontrolle am Flughafen gehen."
        ]
    }
];
