import { CustomWASet } from '../types';

export const WA_SETS: CustomWASet[] = [
  // --- KATEGORIEN NUR ZUM ERKLÄREN ---
  {
    name: 'Objekte', // 30 Erklären-Karten: Fokus auf greifbare, vom Menschen geschaffene Gegenstände
    cards: [
      { id: 'wa-objekte-1', type: 'explain', word: 'Brille', taboos: ['Augen', 'Sehen', 'Gestell', 'Linse', 'Nase'] },
      { id: 'wa-objekte-2', type: 'explain', word: 'Computer', taboos: ['Maus', 'Tastatur', 'Bildschirm', 'Internet', 'Rechner'] },
      { id: 'wa-objekte-3', type: 'explain', word: 'Buch', taboos: ['Lesen', 'Seiten', 'Papier', 'Autor', 'Geschichte'] },
      { id: 'wa-objekte-4', type: 'explain', word: 'Handy', taboos: ['Telefonieren', 'App', 'Nachricht', 'Akku', 'Anrufen'] },
      { id: 'wa-objekte-5', type: 'explain', word: 'Bett', taboos: ['Schlafen', 'Matratze', 'Kissen', 'Müde', 'Nacht'] },
      { id: 'wa-objekte-6', type: 'explain', word: 'Kühlschrank', taboos: ['Essen', 'Kalt', 'Tür', 'Küche', 'Lebensmittel'] },
      { id: 'wa-objekte-7', type: 'explain', word: 'Sofa', taboos: ['Sitzen', 'Wohnzimmer', 'Couch', 'Gemütlich', 'Fernsehen'] },
      { id: 'wa-objekte-8', type: 'explain', word: 'Gitarre', taboos: ['Spielen', 'Saiten', 'Musik', 'Band', 'Klampfe'] },
      { id: 'wa-objekte-9', type: 'explain', word: 'Stuhl', taboos: ['Sitzen', 'Beine', 'Lehne', 'Möbel', 'Holz'] },
      { id: 'wa-objekte-10', type: 'explain', word: 'Tisch', taboos: ['Essen', 'Platte', 'Beine', 'Möbel', 'Stuhl'] },
      { id: 'wa-objekte-11', type: 'explain', word: 'Fenster', taboos: ['Glas', 'Sehen', 'Öffnen', 'Raum', 'Blick'] },
      { id: 'wa-objekte-12', type: 'explain', word: 'Tür', taboos: ['Öffnen', 'Schließen', 'Raum', 'Griff', 'Holz'] },
      { id: 'wa-objekte-13', type: 'explain', word: 'Lampe', taboos: ['Licht', 'Dunkel', 'Birne', 'Anschalten', 'Decke'] },
      { id: 'wa-objekte-14', type: 'explain', word: 'Schlüssel', taboos: ['Tür', 'Öffnen', 'Schloss', 'Bund', 'Metall'] },
      { id: 'wa-objekte-15', type: 'explain', word: 'Spiegel', taboos: ['Bild', 'Sehen', 'Glas', 'Reflexion', 'Gesicht'] },
      { id: 'wa-objekte-16', type: 'explain', word: 'Seife', taboos: ['Waschen', 'Hände', 'Schaum', 'Reinigen', 'Duft'] },
      { id: 'wa-objekte-17', type: 'explain', word: 'Zahnbürste', taboos: ['Zähne', 'Putzen', 'Mund', 'Bürste', 'Pasta'] },
      { id: 'wa-objekte-18', type: 'explain', word: 'Handtuch', taboos: ['Trocknen', 'Nass', 'Stoff', 'Dusche', 'Bad'] },
      { id: 'wa-objekte-19', type: 'explain', word: 'Regenschirm', taboos: ['Regen', 'Nass', 'Schutz', 'Öffnen', 'Zusammenklappen'] },
      { id: 'wa-objekte-20', type: 'explain', word: 'Fernseher', taboos: ['Bildschirm', 'Programm', 'Kanal', 'Fernbedienung', 'Schauen'] },
      { id: 'wa-objekte-21', type: 'explain', word: 'Staubsauger', taboos: ['Saugen', 'Reinigen', 'Dreck', 'Boden', 'Kabel'] },
      { id: 'wa-objekte-22', type: 'explain', word: 'Toaster', taboos: ['Brot', 'Rösten', 'Frühstück', 'Heiß', 'Scheibe'] },
      { id: 'wa-objekte-23', type: 'explain', word: 'Wasserkocher', taboos: ['Wasser', 'Kochen', 'Heiß', 'Tee', 'Kaffee'] },
      { id: 'wa-objekte-24', type: 'explain', word: 'Mikrowelle', taboos: ['Essen', 'Aufwärmen', 'Schnell', 'Welle', 'Gerät'] },
      { id: 'wa-objekte-25', type: 'explain', word: 'Schrank', taboos: ['Kleidung', 'Aufbewahren', 'Tür', 'Holz', 'Möbel'] },
      { id: 'wa-objekte-26', type: 'explain', word: 'Teppich', taboos: ['Boden', 'Weich', 'Muster', 'Wohnzimmer', 'Läufer'] },
      { id: 'wa-objekte-27', type: 'explain', word: 'Vorhang', taboos: ['Fenster', 'Stoff', 'Zuziehen', 'Licht', 'Blickdicht'] },
      { id: 'wa-objekte-28', type: 'explain', word: 'Radio', taboos: ['Hören', 'Musik', 'Nachrichten', 'Sender', 'Antenne'] },
      { id: 'wa-objekte-29', type: 'explain', word: 'Telefon', taboos: ['Anrufen', 'Sprechen', 'Nummer', 'Kabel', 'Hörer'] },
      { id: 'wa-objekte-30', type: 'explain', word: 'Stift', taboos: ['Schreiben', 'Papier', 'Tinte', 'Kappe', 'Zeichnen'] },
    ]
  },
  {
    name: 'Orte', // 30 Erklären-Karten: Fokus auf öffentliche Orte, Gebäude und Umgebungen
    cards: [
      { id: 'wa-orte-1', type: 'explain', word: 'Kino', taboos: ['Film', 'Leinwand', 'Popcorn', 'Sessel', 'Ticket'] },
      { id: 'wa-orte-2', type: 'explain', word: 'Strand', taboos: ['Meer', 'Sand', 'Sonne', 'Wasser', 'Urlaub'] },
      { id: 'wa-orte-3', type: 'explain', word: 'Schule', taboos: ['Lernen', 'Lehrer', 'Klasse', 'Hausaufgaben', 'Unterricht'] },
      { id: 'wa-orte-4', type: 'explain', word: 'Krankenhaus', taboos: ['Arzt', 'Krank', 'Bett', 'Operation', 'Schwester'] },
      { id: 'wa-orte-5', type: 'explain', word: 'Polizei', taboos: ['Auto', 'Uniform', 'Verbrechen', 'Waffe', 'Festnehmen'] },
      { id: 'wa-orte-6', type: 'explain', word: 'Feuerwehr', taboos: ['Rot', 'Schlauch', 'Wasser', 'Brand', 'Löschen'] },
      { id: 'wa-orte-7', type: 'explain', word: 'Supermarkt', taboos: ['Einkaufen', 'Kasse', 'Wagen', 'Regal', 'Lebensmittel'] },
      { id: 'wa-orte-8', type: 'explain', word: 'Bibliothek', taboos: ['Buch', 'Lesen', 'Leise', 'Ausleihen', 'Regal'] },
      { id: 'wa-orte-9', type: 'explain', word: 'Gefängnis', taboos: ['Zelle', 'Gitter', 'Verbrecher', 'Häftling', 'Ausbrechen'] },
      { id: 'wa-orte-10', type: 'explain', word: 'Flughafen', taboos: ['Flugzeug', 'Abflug', 'Ankunft', 'Terminal', 'Passkontrolle'] },
      { id: 'wa-orte-11', type: 'explain', word: 'Hotel', taboos: ['Übernachten', 'Zimmer', 'Bett', 'Rezeption', 'Urlaub'] },
      { id: 'wa-orte-12', type: 'explain', word: 'Berge', taboos: ['Wandern', 'Gipfel', 'Klettern', 'Natur', 'Aussicht'] },
      { id: 'wa-orte-13', type: 'explain', word: 'Wüste', taboos: ['Sand', 'Heiß', 'Kamel', 'Oase', 'Trocken'] },
      { id: 'wa-orte-14', 'type': 'explain', word: 'Dschungel', taboos: ['Grün', 'Tiere', 'Feucht', 'Pflanzen', 'Abenteuer'] },
      { id: 'wa-orte-15', type: 'explain', word: 'Naturpark', taboos: ['Schutz', 'Tiere', 'Pflanzen', 'Wandern', 'Landschaft'] },
      { id: 'wa-orte-16', type: 'explain', word: 'Bahnhof', taboos: ['Zug', 'Gleis', 'Reisen', 'Ankunft', 'Abfahrt'] },
      { id: 'wa-orte-17', type: 'explain', word: 'Museum', taboos: ['Ausstellung', 'Kunst', 'Geschichte', 'Betrachten', 'Exponat'] },
      { id: 'wa-orte-18', type: 'explain', word: 'Park', taboos: ['Grün', 'Bäume', 'Spaziergang', 'Bank', 'Spielen'] },
      { id: 'wa-orte-19', type: 'explain', word: 'Restaurant', taboos: ['Essen', 'Tisch', 'Kellner', 'Speisekarte', 'Bestellen'] },
      { id: 'wa-orte-20', type: 'explain', word: 'Café', taboos: ['Kaffee', 'Kuchen', 'Gemütlich', 'Treffen', 'Tisch'] },
      { id: 'wa-orte-21', type: 'explain', word: 'Bank', taboos: ['Geld', 'Konto', 'Abheben', 'Einzahlen', 'Schalter'] },
      { id: 'wa-orte-22', type: 'explain', word: 'Postamt', taboos: ['Brief', 'Paket', 'Versenden', 'Marke', 'Schalter'] },
      { id: 'wa-orte-23', type: 'explain', word: 'Kirche', taboos: ['Gottesdienst', 'Glaube', 'Beten', 'Turm', 'Glocken'] },
      { id: 'wa-orte-24', type: 'explain', word: 'Theater', taboos: ['Bühne', 'Schauspiel', 'Stück', 'Vorhang', 'Applaus'] },
      { id: 'wa-orte-25', type: 'explain', word: 'Stadion', taboos: ['Sport', 'Spiel', 'Zuschauer', 'Feld', 'Tor'] },
      { id: 'wa-orte-26', type: 'explain', word: 'Zoo', taboos: ['Tiere', 'Käfig', 'Besucher', 'Füttern', 'Gehege'] },
      { id: 'wa-orte-27', type: 'explain', word: 'Universität', taboos: ['Studieren', 'Student', 'Vorlesung', 'Campus', 'Abschluss'] },
      { id: 'wa-orte-28', type: 'explain', word: 'Gericht', taboos: ['Urteil', 'Anwalt', 'Richter', 'Prozess', 'Gerechtigkeit'] },
      { id: 'wa-orte-29', type: 'explain', word: 'Amt', taboos: ['Behörde', 'Formular', 'Warten', 'Bürokratie', 'Dokumente'] },
      { id: 'wa-orte-30', type: 'explain', word: 'Markt', taboos: ['Kaufen', 'Verkaufen', 'Stand', 'Frisch', 'Obst'] },
    ]
  },
  {
    name: 'Ereignisse', // 30 Erklären-Karten: Fokus auf Ereignisse, Feiern, Naturphänomene und abstrakte Konzepte
    cards: [
      { id: 'wa-ereignisse-1', type: 'explain', word: 'Geburtstag', taboos: ['Feier', 'Geschenk', 'Kuchen', 'Kerzen', 'Alter'] },
      { id: 'wa-ereignisse-2', type: 'explain', word: 'Hochzeit', taboos: ['Heiraten', 'Ring', 'Braut', 'Kirche', 'Ja-Wort'] },
      { id: 'wa-ereignisse-3', type: 'explain', word: 'Regen', taboos: ['Wasser', 'Nass', 'Wolken', 'Schirm', 'Tropfen'] },
      { id: 'wa-ereignisse-4', type: 'explain', word: 'Schnee', taboos: ['Kalt', 'Weiß', 'Winter', 'Flocken', 'Schneemann'] },
      { id: 'wa-ereignisse-5', type: 'explain', word: 'Sonne', taboos: ['Himmel', 'Warm', 'Licht', 'Scheinen', 'Tag'] },
      { id: 'wa-ereignisse-6', type: 'explain', word: 'Musik', taboos: ['Hören', 'Lied', 'Singen', 'Instrument', 'Radio'] },
      { id: 'wa-ereignisse-7', type: 'explain', word: 'Tanz', taboos: ['Bewegung', 'Musik', 'Beine', 'Rhythmus', 'Disco'] },
      { id: 'wa-ereignisse-8', type: 'explain', word: 'Gewitter', taboos: ['Blitz', 'Donner', 'Sturm', 'Regen', 'Dunkel'] },
      { id: 'wa-ereignisse-9', type: 'explain', word: 'Erdbeben', taboos: ['Boden', 'Beben', 'Zerstörung', 'Plötzlich', 'Naturkatastrophe'] },
      { id: 'wa-ereignisse-10', type: 'explain', word: 'Vulkan', taboos: ['Feuer', 'Lava', 'Berg', 'Ausbruch', 'Rauch'] },
      { id: 'wa-ereignisse-11', type: 'explain', word: 'Sturm', taboos: ['Wind', 'Böen', 'Regen', 'Zerstörung', 'Wetter'] },
      { id: 'wa-ereignisse-12', type: 'explain', word: 'Feiertag', taboos: ['Frei', 'Fest', 'Besonderer Tag', 'Feiern', 'Tradition'] },
      { id: 'wa-ereignisse-13', type: 'explain', word: 'Konzert', taboos: ['Musik', 'Bühne', 'Zuschauer', 'Singen', 'Instrumente'] },
      { id: 'wa-ereignisse-14', type: 'explain', word: 'Festival', taboos: ['Musik', 'Feiern', 'Open Air', 'Zelte', 'Sommer'] },
      { id: 'wa-ereignisse-15', type: 'explain', word: 'Parade', taboos: ['Umzug', 'Feier', 'Straße', 'Zuschauer', 'Musik'] },
      { id: 'wa-ereignisse-16', type: 'explain', word: 'Wahl', taboos: ['Stimme', 'Politik', 'Entscheidung', 'Kandidat', 'Kreuz'] },
      { id: 'wa-ereignisse-17', type: 'explain', word: 'Unfall', taboos: ['Schaden', 'Plötzlich', 'Verletzung', 'Pech', 'Ereignis'] },
      { id: 'wa-ereignisse-18', type: 'explain', word: 'Ernte', taboos: ['Feld', 'Pflanzen', 'Sammeln', 'Herbst', 'Landwirtschaft'] },
      { id: 'wa-ereignisse-19', type: 'explain', word: 'Sonnenuntergang', taboos: ['Abend', 'Himmel', 'Farben', 'Ende', 'Tag'] },
      { id: 'wa-ereignisse-20', type: 'explain', word: 'Sonnenaufgang', taboos: ['Morgen', 'Himmel', 'Neu', 'Beginn', 'Tag'] },
      { id: 'wa-ereignisse-21', type: 'explain', word: 'Mondfinsternis', taboos: ['Mond', 'Dunkel', 'Schatten', 'Himmel', 'Selten'] },
      { id: 'wa-ereignisse-22', type: 'explain', word: 'Sternschnuppe', taboos: ['Stern', 'Wunsch', 'Himmel', 'Fallen', 'Nacht'] },
      { id: 'wa-ereignisse-23', type: 'explain', word: 'Karneval', taboos: ['Kostüm', 'Feiern', 'Umzug', 'Verkleiden', 'Närrisch'] },
      { id: 'wa-ereignisse-24', type: 'explain', word: 'Weihnachten', taboos: ['Fest', 'Geschenke', 'Baum', 'Familie', 'Dezember'] },
      { id: 'wa-ereignisse-25', type: 'explain', word: 'Ostern', taboos: ['Ei', 'Hase', 'Frühling', 'Fest', 'Suchen'] },
      { id: 'wa-ereignisse-26', type: 'explain', word: 'Silvester', taboos: ['Neujahr', 'Feuerwerk', 'Feiern', 'Mitternacht', 'Countdown'] },
      { id: 'wa-ereignisse-27', type: 'explain', word: 'Prüfung', taboos: ['Test', 'Lernen', 'Schule', 'Ergebnis', 'Angst'] },
      { id: 'wa-ereignisse-28', type: 'explain', word: 'Interview', taboos: ['Fragen', 'Antworten', 'Job', 'Gespräch', 'Kennenlernen'] },
      { id: 'wa-ereignisse-29', type: 'explain', word: 'Meeting', taboos: ['Besprechung', 'Arbeit', 'Tisch', 'Diskussion', 'Entscheidung'] },
      { id: 'wa-ereignisse-30', type: 'explain', word: 'Präsentation', taboos: ['Vortrag', 'Folien', 'Sprechen', 'Publikum', 'Zeigen'] },
    ]
  },

  // --- KATEGORIEN NUR FÜR PANTOMIME ---
  {
    name: 'Haushalt', // 30 Pantomime-Karten: Fokus auf häusliche Tätigkeiten und Körperpflege
    cards: [
      { id: 'wap-haushalt-1', type: 'pantomime', word: 'Zähne putzen' },
      { id: 'wap-haushalt-2', type: 'pantomime', word: 'Staubsaugen' },
      { id: 'wap-haushalt-3', type: 'pantomime', word: 'Haare kämmen' },
      { id: 'wap-haushalt-4', type: 'pantomime', word: 'Sich schminken' },
      { id: 'wap-haushalt-5', type: 'pantomime', word: 'Fenster putzen' },
      { id: 'wap-haushalt-6', type: 'pantomime', word: 'Socken anziehen' },
      { id: 'wap-haushalt-7', type: 'pantomime', word: 'Baby wickeln' },
      { id: 'wap-haushalt-8', type: 'pantomime', word: 'Wäsche aufhängen' },
      { id: 'wap-haushalt-9', type: 'pantomime', word: 'Boden wischen' },
      { id: 'wap-haushalt-10', type: 'pantomime', word: 'Betten machen' },
      { id: 'wap-haushalt-11', type: 'pantomime', word: 'Blumen gießen' },
      { id: 'wap-haushalt-12', type: 'pantomime', word: 'Müll rausbringen' },
      { id: 'wap-haushalt-13', type: 'pantomime', word: 'Geschirr spülen' },
      { id: 'wap-haushalt-14', type: 'pantomime', word: 'Staub wischen' },
      { id: 'wap-haushalt-15', type: 'pantomime', word: 'Kleidung bügeln' },
      { id: 'wap-haushalt-16', type: 'pantomime', word: 'Duschen' },
      { id: 'wap-haushalt-17', type: 'pantomime', word: 'Hände waschen' },
      { id: 'wap-haushalt-18', type: 'pantomime', word: 'Nägel schneiden' },
      { id: 'wap-haushalt-19', type: 'pantomime', word: 'Sich rasieren' },
      { id: 'wap-haushalt-20', type: 'pantomime', word: 'Haare föhnen' },
      { id: 'wap-haushalt-21', type: 'pantomime', word: 'Einen Besen schwingen' },
      { id: 'wap-haushalt-22', type: 'pantomime', word: 'Einen Spiegel putzen' },
      { id: 'wap-haushalt-23', type: 'pantomime', word: 'Pflanzen umtopfen' },
      { id: 'wap-haushalt-24', type: 'pantomime', word: 'Glühbirne wechseln' },
      { id: 'wap-haushalt-25', type: 'pantomime', word: 'Batterien wechseln' },
      { id: 'wap-haushalt-26', type: 'pantomime', word: 'Bilder aufhängen' },
      { id: 'wap-haushalt-27', type: 'pantomime', word: 'Vorhänge zuziehen' },
      { id: 'wap-haushalt-28', type: 'pantomime', word: 'Teppich klopfen' },
      { id: 'wap-haushalt-29', type: 'pantomime', word: 'Kaminholz stapeln' },
      { id: 'wap-haushalt-30', type: 'pantomime', word: 'Möbel rücken' },
    ]
  },
  {
    name: 'Sport', // 30 Pantomime-Karten: Fokus auf sportliche Aktivitäten
    cards: [
      { id: 'wap-sport-1', type: 'pantomime', word: 'Fußball spielen' },
      { id: 'wap-sport-2', type: 'pantomime', word: 'Basketball werfen' },
      { id: 'wap-sport-3', type: 'pantomime', word: 'Tennis spielen' },
      { id: 'wap-sport-4', type: 'pantomime', word: 'Schwimmen' },
      { id: 'wap-sport-5', type: 'pantomime', word: 'Yoga machen' },
      { id: 'wap-sport-6', type: 'pantomime', word: 'Radfahren' },
      { id: 'wap-sport-7', type: 'pantomime', word: 'Boxen' },
      { id: 'wap-sport-8', type: 'pantomime', word: 'Golf spielen' },
      { id: 'wap-sport-9', type: 'pantomime', word: 'Bowling spielen' },
      { id: 'wap-sport-10', type: 'pantomime', word: 'Eishockey spielen' },
      { id: 'wap-sport-11', type: 'pantomime', word: 'Handball werfen' },
      { id: 'wap-sport-12', type: 'pantomime', word: 'Volleyball spielen' },
      { id: 'wap-sport-13', type: 'pantomime', word: 'Badminton spielen' },
      { id: 'wap-sport-14', type: 'pantomime', word: 'Tischtennis spielen' },
      { id: 'wap-sport-15', type: 'pantomime', word: 'Fechten' },
      { id: 'wap-sport-16', type: 'pantomime', word: 'Reiten' },
      { id: 'wap-sport-17', type: 'pantomime', word: 'Rudern' },
      { id: 'wap-sport-18', type: 'pantomime', word: 'Kanu fahren' },
      { id: 'wap-sport-19', type: 'pantomime', word: 'Segeln' },
      { id: 'wap-sport-20', type: 'pantomime', word: 'Surfen' },
      { id: 'wap-sport-21', type: 'pantomime', word: 'Skateboard fahren' },
      { id: 'wap-sport-22', type: 'pantomime', word: 'Snowboard fahren' },
      { id: 'wap-sport-23', type: 'pantomime', word: 'Leichtathletik (Sprint)' },
      { id: 'wap-sport-24', type: 'pantomime', word: 'Turnen (Radschlag)' },
      { id: 'wap-sport-25', type: 'pantomime', word: 'Gewichtheben' },
      { id: 'wap-sport-26', type: 'pantomime', word: 'Tanzen (Hip-Hop)' },
      { id: 'wap-sport-27', type: 'pantomime', word: 'Klettern (Indoor)' },
      { id: 'wap-sport-28', 'type': 'pantomime', word: 'Eislaufen' },
      { id: 'wap-sport-29', 'type': 'pantomime', word: 'Rollschuh fahren' },
      { id: 'wap-sport-30', 'type': 'pantomime', word: 'Dart werfen' },
    ]
  },
  {
    name: 'Küche', // 30 Pantomime-Karten: Fokus auf Aktivitäten rund ums Kochen und Essen
    cards: [
      { id: 'wap-kueche-1', type: 'pantomime', word: 'Essen kochen' },
      { id: 'wap-kueche-2', type: 'pantomime', word: 'Kuchen backen' },
      { id: 'wap-kueche-3', type: 'pantomime', word: 'Gemüse schneiden' },
      { id: 'wap-kueche-4', 'type': 'pantomime', word: 'Spülen' },
      { id: 'wap-kueche-5', type: 'pantomime', word: 'Kaffee kochen' },
      { id: 'wap-kueche-6', type: 'pantomime', word: 'Brot schneiden' },
      { id: 'wap-kueche-7', type: 'pantomime', word: 'Ei braten' },
      { id: 'wap-kueche-8', type: 'pantomime', word: 'Suppe umrühren' },
      { id: 'wap-kueche-9', type: 'pantomime', word: 'Salat zubereiten' },
      { id: 'wap-kueche-10', type: 'pantomime', word: 'Pizza belegen' },
      { id: 'wap-kueche-11', type: 'pantomime', word: 'Toast machen' },
      { id: 'wap-kueche-12', type: 'pantomime', word: 'Milch aufschäumen' },
      { id: 'wap-kueche-13', type: 'pantomime', word: 'Abwaschen' },
      { id: 'wap-kueche-14', type: 'pantomime', word: 'Tisch decken' },
      { id: 'wap-kueche-15', type: 'pantomime', word: 'Tisch abräumen' },
      { id: 'wap-kueche-16', type: 'pantomime', word: 'Einkaufstasche tragen' },
      { id: 'wap-kueche-17', type: 'pantomime', word: 'Kühlschrank öffnen' },
      { id: 'wap-kueche-18', type: 'pantomime', word: 'Ofen vorheizen' },
      { id: 'wap-kueche-19', type: 'pantomime', word: 'Nudeln kochen' },
      { id: 'wap-kueche-20', type: 'pantomime', word: 'Getränk einschenken' },
      { id: 'wap-kueche-21', type: 'pantomime', word: 'Mixer benutzen' },
      { id: 'wap-kueche-22', type: 'pantomime', word: 'Waffeln backen' },
      { id: 'wap-kueche-23', type: 'pantomime', word: 'Pfannkuchen wenden' },
      { id: 'wap-kueche-24', type: 'pantomime', word: 'Grillen' },
      { id: 'wap-kueche-25', type: 'pantomime', word: 'Besteck polieren' },
      { id: 'wap-kueche-26', type: 'pantomime', word: 'Gewürze suchen' },
      { id: 'wap-kueche-27', type: 'pantomime', word: 'Teig kneten' },
      { id: 'wap-kueche-28', type: 'pantomime', word: 'Kekse ausstechen' },
      { id: 'wap-kueche-29', type: 'pantomime', word: 'Eisportionierer benutzen' },
      { id: 'wap-kueche-30', type: 'pantomime', word: 'Flasche öffnen' },
    ]
  },

  // --- GEMISCHTE KATEGORIE ---
  {
    name: 'Natur', // 30 Erklären-Karten + 30 Pantomime-Karten = 60 Karten
    cards: [
      // Erklären-Karten (30 Stück)
      { id: 'wa-natur-1', type: 'explain', word: 'Berg', taboos: ['Hoch', 'Gipfel', 'Klettern', 'Stein', 'Aussicht'] },
      { id: 'wa-natur-2', type: 'explain', word: 'Fluss', taboos: ['Wasser', 'Strömung', 'Ufer', 'Boot', 'Fisch'] },
      { id: 'wa-natur-3', type: 'explain', word: 'See', taboos: ['Wasser', 'Ufer', 'Schwimmen', 'Boot', 'Spiegelung'] },
      { id: 'wa-natur-4', type: 'explain', word: 'Ozean', taboos: ['Meer', 'Salz', 'Wellen', 'Tief', 'Blau'] },
      { id: 'wa-natur-5', type: 'explain', word: 'Wald', taboos: ['Bäume', 'Grün', 'Tiere', 'Dunkel', 'Spaziergang'] },
      { id: 'wa-natur-6', type: 'explain', word: 'Wiese', taboos: ['Gras', 'Blumen', 'Grün', 'Flach', 'Tier'] },
      { id: 'wa-natur-7', type: 'explain', word: 'Blatt', taboos: ['Baum', 'Grün', 'Herbst', 'Fallen', 'Pflanze'] },
      { id: 'wa-natur-8', type: 'explain', word: 'Wurzel', taboos: ['Baum', 'Erde', 'Halten', 'Pflanze', 'Unten'] },
      { id: 'wa-natur-9', type: 'explain', word: 'Vogel', taboos: ['Fliegen', 'Feder', 'Nest', 'Zwitschern', 'Tier'] },
      { id: 'wa-natur-10', type: 'explain', word: 'Fisch', taboos: ['Wasser', 'Schwimmen', 'Flosse', 'Schuppen', 'Tier'] },
      { id: 'wa-natur-11', type: 'explain', word: 'Insekt', taboos: ['Klein', 'Fliegen', 'Krabbe', 'Sechs Beine', 'Tier'] },
      { id: 'wa-natur-12', type: 'explain', word: 'Pilz', taboos: ['Wald', 'Hut', 'Sporen', 'Sammeln', 'Giftig'] },
      { id: 'wa-natur-13', type: 'explain', word: 'Mond', taboos: ['Nacht', 'Himmel', 'Silber', 'Kreis', 'Leuchten'] },
      { id: 'wa-natur-14', type: 'explain', word: 'Stern', taboos: ['Nacht', 'Himmel', 'Funkeln', 'Klein', 'Leuchten'] },
      { id: 'wa-natur-15', type: 'explain', word: 'Wolke', taboos: ['Himmel', 'Weiß', 'Regen', 'Form', 'Fluffy'] },
      { id: 'wa-natur-16', type: 'explain', word: 'Wetter', taboos: ['Klima', 'Sonne', 'Regen', 'Wind', 'Temperatur'] },
      { id: 'wa-natur-17', type: 'explain', word: 'Klima', taboos: ['Wetter', 'Erde', 'Temperatur', 'Veränderung', 'Zone'] },
      { id: 'wa-natur-18', type: 'explain', word: 'Insel', taboos: ['Meer', 'Land', 'Einsam', 'Strand', 'Ufer'] },
      { id: 'wa-natur-19', type: 'explain', word: 'Höhle', taboos: ['Dunkel', 'Fels', 'Unterirdisch', 'Tropfstein', 'Fledermaus'] },
      { id: 'wa-natur-20', type: 'explain', word: 'Welle', taboos: ['Meer', 'Wasser', 'Brandung', 'Surfen', 'Bewegung'] },
      { id: 'wa-natur-21', type: 'explain', word: 'Küste', taboos: ['Meer', 'Land', 'Strand', 'Felsen', 'Ufer'] },
      { id: 'wa-natur-22', type: 'explain', word: 'Tal', taboos: ['Berge', 'Fluss', 'Senke', 'Landschaft', 'Grün'] },
      { id: 'wa-natur-23', type: 'explain', word: 'Gletscher', taboos: ['Eis', 'Berg', 'Kalt', 'Schmelzen', 'Bewegen'] },
      { id: 'wa-natur-24', type: 'explain', word: 'Regenbogen', taboos: ['Farben', 'Regen', 'Sonne', 'Bogen', 'Himmel'] },
      { id: 'wa-natur-25', type: 'explain', word: 'Blitz', taboos: ['Gewitter', 'Donner', 'Himmel', 'Licht', 'Gefahr'] },
      { id: 'wa-natur-26', type: 'explain', word: 'Donner', taboos: ['Gewitter', 'Blitz', 'Laut', 'Geräusch', 'Himmel'] },
      { id: 'wa-natur-27', type: 'explain', word: 'Wind', taboos: ['Luft', 'Bewegung', 'Wehen', 'Sturm', 'Frisch'] },
      { id: 'wa-natur-28', type: 'explain', word: 'Nebel', taboos: ['Dicht', 'Sicht', 'Feucht', 'Morgen', 'Mysteriös'] },
      { id: 'wa-natur-29', type: 'explain', word: 'Tautropfen', taboos: ['Morgen', 'Gras', 'Glänzen', 'Klein', 'Feucht'] },
      { id: 'wa-natur-30', type: 'explain', word: 'Bach', taboos: ['Fluss', 'Klein', 'Plätschern', 'Wald', 'Wasser'] },
      // Pantomime-Karten (30 Stück)
      { id: 'wap-natur-1', type: 'pantomime', word: 'Einen Baum umarmen' },
      { id: 'wap-natur-2', type: 'pantomime', word: 'Blumen pflücken' },
      { id: 'wap-natur-3', type: 'pantomime', word: 'Vögel beobachten' },
      { id: 'wap-natur-4', type: 'pantomime', word: 'Fische füttern' },
      { id: 'wap-natur-5', type: 'pantomime', word: 'Einen Schmetterling fangen' },
      { id: 'wap-natur-6', type: 'pantomime', word: 'Auf einem Felsen klettern' },
      { id: 'wap-natur-7', type: 'pantomime', word: 'Im Fluss schwimmen' },
      { id: 'wap-natur-8', type: 'pantomime', word: 'Samen säen' },
      { id: 'wap-natur-9', type: 'pantomime', word: 'Einen Regenbogen zeigen' },
      { id: 'wap-natur-10', type: 'pantomime', word: 'Ein Nest bauen' },
      { id: 'wap-natur-11', type: 'pantomime', word: 'Eine Höhle erkunden' },
      { id: 'wap-natur-12', type: 'pantomime', word: 'Ein Lagerfeuer machen' },
      { id: 'wap-natur-13', type: 'pantomime', word: 'Pilze sammeln' },
      { id: 'wap-natur-14', type: 'pantomime', word: 'Im Gras liegen' },
      { id: 'wap-natur-15', type: 'pantomime', word: 'Einen Bach überqueren' },
      { id: 'wap-natur-16', type: 'pantomime', word: 'Sonne genießen' },
      { id: 'wap-natur-17', type: 'pantomime', word: 'Regen spüren' },
      { id: 'wap-natur-18', type: 'pantomime', word: 'Wind in den Haaren' },
      { id: 'wap-natur-19', type: 'pantomime', word: 'Schneeengel machen' },
      { id: 'wap-natur-20', type: 'pantomime', word: 'Tierstimmen nachahmen' },
      { id: 'wap-natur-21', type: 'pantomime', word: 'Ein Blatt aufheben' },
      { id: 'wap-natur-22', type: 'pantomime', word: 'Eine Blume riechen' },
      { id: 'wap-natur-23', type: 'pantomime', word: 'Vogelnester suchen' },
      { id: 'wap-natur-24', type: 'pantomime', word: 'Fische beobachten' },
      { id: 'wap-natur-25', type: 'pantomime', word: 'Insekten verfolgen' },
      { id: 'wap-natur-26', type: 'pantomime', word: 'Einen Pilz suchen' },
      { id: 'wap-natur-27', type: 'pantomime', word: 'Sterne beobachten' },
      { id: 'wap-natur-28', type: 'pantomime', word: 'Wellen am Strand genießen' },
      { id: 'wap-natur-29', type: 'pantomime', word: 'Einen Wasserfall bestaunen' },
      { id: 'wap-natur-30', type: 'pantomime', word: 'Einen Baum fällen' },
    ]
  },
];
